swagger: "2.0"
info:
  description: "This document is for backend service restful api"
  version: "0.0.1"
  title: "CatWar"
host: "localhost"
basePath: "/v1"
tags:
- name: "Battle"
  description: "Battle operation"
schemes:
- "https"
paths:
  /battle:
    post:
      tags:
      - "Battle"
      summary: "Enter a battle"
      description: "This api for entering a battle"
      operationId: "postBattle"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Character information to enter a battle."
        required: true
        schema:
          $ref: "#/definitions/EnterBattleBody"
      responses:
        201:
          description: "Getting rsponse successfully."
          schema:
            $ref: "#/definitions/Battle"
      security:
      - api_key: []
    delete:
      tags:
      - "Battle"
      summary: "Exit a battle"
      description: "This api for exiting a battle"
      operationId: "deleteBattle"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Battle result information to exit the battle."
        required: true
        schema:
          $ref: "#/definitions/ExitBattleBody"
      responses:
        200:
          description: "Getting rsponse successfully."
          schema:
            $ref: "#/definitions/BattleResult"
      security:
      - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Location:
    type: "object"
    properties:
      map_id:
        type: "string"
        description: "Identity of the map."
        example: "map-001"
      x:
        type: "integer"
        format: "int64"
        description: "X axis of the map."
        example: "130"
      y:
        type: "integer"
        format: "int64"
        description: "Y axis of the map."
        example: "20"
  EnterBattleBody:
    type: "object"
    properties:
      location:
        $ref: "#/definitions/Location"
      user_info:
        type: "string"
        description: "尚未定義"
        example: "尚未定義"
  ExitBattleBody:
    type: "object"
    properties:
      battle_id:
        type: "string"
        description: "Identity of the battle."
        example: "battle-4f037236-9422-42bc-a1ae-cfe36e8bcdee"
      result:
        type: "string"
        enum:
          - "succeed"
          - "failed"
          - "escaped"
        description: "Battle result"
        example: "succeed"
      current_hp:
        type: "integer"
        format: "int64"
        description: "Current health points of the character."
        example: "81000"
      current_mp:
        type: "integer"
        format: "int64"
        description: "Current magic points of the character."
        example: "81000"
  EnhanceBasicProperty:
    type: "object"
    properties:
      enhancement_id:
        type: "string"
        format: "string"
        description: "增益編號。每個編號代表不同增益，例如:編號001代表攻擊增加3%，編號005代表製作率增加5%"
        example: "enhancement-id-cc36d2ff-74e9-47e2-9418-7a642adf85ec"
      attack_enhance_ratio:
        type: "number"
        format: "float"
        description: "攻擊增益百分比(EX : 基本攻擊100，攻擊增益百分比1.5，總攻擊=100*(1+1.5%)=101.5)"
        example: "1.5"
      defense_enhance_ratio:
        type: "number"
        format: "float"
        description: "防禦增益百分比(EX : 基本防禦100，防禦增益百分比1.5，總防禦=100*(1+1.5%)=101.5)"
        example: "1.5"
      hp_enhance_ratio:
        type: "number"
        format: "float"
        description: "最大血量增益百分比(EX : 基本血量100，最大血量增益百分比1.5，總血量=100*(1+1.5%)=101.5)"
        example: "1.5"
      mp_enhance_ratio:
        type: "number"
        format: "float"
        description: "最大氣量增益百分比(EX : 基本氣量100，最大氣量增益百分比1.5，總氣量=100*(1+1.5%)=101.5)"
        example: "1.5"
      critical_ratio:
        type: "number"
        format: "float"
        description: "爆擊率百分比"
        example: "1.5"
      critical_attack_ratio:
        type: "number"
        format: "float"
        description: "爆擊傷害百分比(EX : 總攻擊100，爆擊傷害百分比150，輸出=100*(1+150%)=250)"
        example: "150"
      item_enhance_ratio:
        type: "number"
        format: "float"
        description: "物品強化機率"
        example: "60"
      item_craft_ratio:
        type: "number"
        format: "float"
        description: "物品製作機率"
        example: "60"
      speed_enhance_ratio:
        type: "number"
        format: "float"
        description: "速度增益百分比(EX : 基本速度100，速度增益百分比1.5，總速度=100*(1+1.5%)=101.5)"
        example: "1.5"
  BasicProperty:
    type: "object"
    properties:
      max_hp:
        type: "integer"
        format: "int64"
        description: "Max health points of the character."
        example: "87000"
      current_hp:
        type: "integer"
        format: "int64"
        description: "Current health points of the character."
        example: "81000"
      max_mp:
        type: "integer"
        format: "int64"
        description: "Max magic points of the character."
        example: "87000"
      current_mp:
        type: "integer"
        format: "int64"
        description: "Current magic points of the character."
        example: "81000"
      attack:
        type: "integer"
        format: "int64"
        description: "Attack of the character."
        example: "150"
      defense:
        type: "integer"
        format: "int64"
        description: "Defense of the character."
        example: "80"
      speed:
        type: "integer"
        format: "int64"
        description: "Speed of the character."
        example: "100"
  Item:
    type: "object"
    properties:
      item_id:
        type: "string"
        format: "string"
        description: "道具編號。例如001代表鐵釘，002代表果實"
        example: "item-id-cc36d2ff-74e9-47e2-9418-7a642adf85ec"
      item_basic_property:
        $ref: "#/definitions/BasicProperty"
      item_enhance_basic_property:
        type: "array"
        items:
          $ref: "#/definitions/EnhanceBasicProperty"
      item_price:
        type: "integer"
        format: "int64"
        description: "道具售價"
        example: "8000"
      item_description:
        type: "string"
        format: "string"
        description: "道具說明"
        example: "用鐵製成的棒子。用來移動沉重的物品。偶爾危急時，也能當作其他用途使用。"
  Battle:
    type: "object"
    properties:
      battle_id:
        type: "string"
        description: "Identity of the battle."
        example: "battle-4f037236-9422-42bc-a1ae-cfe36e8bcdee"
      monsters:
        type: "array"
        items:
          type: "string"
          format: "string"
          description: "Monster id"
          example: "monster-00001"
      items:
        type: "array"
        items:
          $ref: "#/definitions/Item"
  BattleResult:
    type: "object"
    properties:
      experience:
        type: "integer"
        format: "int64"
        description: "戰役結束後所增加的經驗值."
        example: "81000"
