swagger: "2.0"
info:
  description: "This document is for backend service restful api"
  version: "0.0.1"
  title: "CatWar"
host: "localhost"
basePath: "/v1"
tags:
- name: "Character"
  description: "Character operation"
schemes:
- "https"
paths:
  /character:
    post:
      tags:
      - "Character"
      summary: "Create a character"
      description: "This api for creating a character by given parameters."
      operationId: "postCharacter"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Character information to be created."
        required: true
        schema:
          $ref: "#/definitions/CreateCharacter"
      responses:
        201:
          description: "Getting rsponse successfully."
          schema:
            $ref: "#/definitions/Character"
      security:
      - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  CreateCharacter:
    type: "object"
    properties:
      character_name:
        type: "string"
        description: "Character name to be created."
        example: "風間翔"
      country:
        type: "string"
        description: "Country of the character."
        example: "北境王國"
      career:
        type: "string"
        description: "Career of the character."
        example: "術士"
  SavePoint:
    type: "object"
    properties:
      map_id:
        type: "string"
        description: "Identity of the map."
        example: "map-001"
      x:
        type: "integer"
        format: "int64"
        description: "X axis of the map."
        example: "130"
      y:
        type: "integer"
        format: "int64"
        description: "Y axis of the map."
        example: "20"
  EnhanceBasicProperty:
    type: "object"
    properties:
      attack_enhance_ratio:
        type: "number"
        format: "float"
        description: "攻擊增益百分比(EX : 基本攻擊100，攻擊增益百分比1.5，總攻擊=100*(1+1.5%)=101.5)"
        example: "1.5"
      defense_enhance_ratio:
        type: "number"
        format: "float"
        description: "防禦增益百分比(EX : 基本防禦100，防禦增益百分比1.5，總防禦=100*(1+1.5%)=101.5)"
        example: "1.5"
      hp_enhance_ratio:
        type: "number"
        format: "float"
        description: "最大血量增益百分比(EX : 基本血量100，最大血量增益百分比1.5，總血量=100*(1+1.5%)=101.5)"
        example: "1.5"
      mp_enhance_ratio:
        type: "number"
        format: "float"
        description: "最大氣量增益百分比(EX : 基本氣量100，最大氣量增益百分比1.5，總氣量=100*(1+1.5%)=101.5)"
        example: "1.5"
      critical_ratio:
        type: "number"
        format: "float"
        description: "爆擊率百分比"
        example: "1.5"
      critical_attack_ratio:
        type: "number"
        format: "float"
        description: "爆擊傷害百分比(EX : 總攻擊100，爆擊傷害百分比150，輸出=100*(1+150%)=250)"
        example: "150"
      item_enhance_ratio:
        type: "number"
        format: "float"
        description: "物品強化機率"
        example: "60"
      item_craft_ratio:
        type: "number"
        format: "float"
        description: "物品製作機率"
        example: "60"
      speed_enhance_ratio:
        type: "number"
        format: "float"
        description: "速度增益百分比(EX : 基本速度100，速度增益百分比1.5，總速度=100*(1+1.5%)=101.5)"
        example: "1.5"
  BasicProperty:
    type: "object"
    properties:
      max_hp:
        type: "integer"
        format: "int64"
        description: "Max health points of the character."
        example: "87000"
      current_hp:
        type: "integer"
        format: "int64"
        description: "Current health points of the character."
        example: "81000"
      max_mp:
        type: "integer"
        format: "int64"
        description: "Max magic points of the character."
        example: "87000"
      current_mp:
        type: "integer"
        format: "int64"
        description: "Current magic points of the character."
        example: "81000"
      attack:
        type: "integer"
        format: "int64"
        description: "Attack of the character."
        example: "150"
      defense:
        type: "integer"
        format: "int64"
        description: "Defense of the character."
        example: "80"
      speed:
        type: "integer"
        format: "int64"
        description: "Speed of the character."
        example: "100"
  Character:
    type: "object"
    properties:
      character_name:
        type: "string"
        description: "Name of the character."
        example: "風間翔"
      country:
        type: "string"
        description: "Name of the country."
        example: "北境王國"
      career:
        type: "string"
        description: "Career of the character."
        example: "術士"
      level:
        type: "integer"
        format: "int64"
        description: "Level of the character."
        example: "87"
      current_experience:
        type: "integer"
        format: "int64"
        description: "Current experience of the character."
        example: "23000000"
      next_level_experience:
        type: "integer"
        format: "int64"
        description: "Next level experience of the character."
        example: "80000"
      money:
        type: "integer"
        format: "int64"
        description: "Money of the character."
        example: "8888888"
      save_point:
        $ref: "#/definitions/SavePoint"
      available_skill_point:
        type: "integer"
        format: "int64"
        description: "Available skill points of the character."
        example: "3"
      skill_tree:
        type: "array"
        items:
          type: "string"
          format: "string"
          description: "Skill identity."
          example: "skill-001"
      type:
        type: "string"
        format: "string"
        description: "Property value of the character such as 火, 冰, 風, 光, 暗"
        example: "冰"
      basic_property:
        $ref: "#/definitions/BasicProperty"
